- name: Collect BIG-IP facts to determine HA pairs
  bigip_device_info:
    gather_subset:
      - devices
    provider: "{{ provider }}"
  register: ha_pairs


- name: Initialize active device fact
  set_fact:
    active_host: False


- name: Set active
  set_fact:
    active_host: True
  when:
    - inventory_hostname == "{{ device.hostname }}"
    - device.failover_state == "active"
  loop: "{{ ha_pairs.devices }}"
  loop_control:
    loop_var: device

- name: debug active device fact
  debug:
    var: active_host 
