---
- name: Populate the HA IP
  set_fact:
    ha_ips: "{{ ha_ips | combine({inventory_hostname_short: VirtualMachine_Network3_Address}, recursive=True) }}"

- name: write ha_ips var to file
  copy:
    content: "{{ ha_ips | to_nice_json }}"
    dest: "{{role_path}}/tmp/{{inventory_hostname_short}}-ha.json"
