---
- name: load vars from file
  include_vars:
    files_matching: .json
    dir: "{{role_path}}/tmp/"
    name: ha_ips_from_file

- name: Populate the HA IP Peers
  set_fact:
    ha_peer_ip: "{{ item.value }}"
  when: inventory_hostname_short not in item.key
  with_dict: "{{ ha_ips_from_file }}"
