---

- name: Get floating IP's 
  block:
    - name: Get an IP from IPAM for the external float
      nios_host_record:
        name: "{{ inventory_hostname }}"
        ipv4addrs:
          - ipv4addr: "{{ lookup('nios_next_ip', '192.168.254.0/24', provider=nios_provider)[0] }}"
        state: present
        provider: "{{nios_provider}}"
      register: externalFloat

    - name: Get an IP from IPAM for the internal Red float
      nios_host_record:
        name: "{{ inventory_hostname }}"
        ipv4addrs:
          - ipv4addr: "{{ lookup('nios_next_ip', '192.168.252.0/24', provider=nios_provider)[0] }}"
        state: present
        provider: "{{nios_provider}}"
      register: internalFloat
  run_once: true