


- import_tasks: build_provider.yaml
  tags:
    - buildApp

- import_tasks: populate_status.yaml
  tags:
    - buildApp

- import_tasks: cleanup_temp_directories.yaml
  tags:
    - buildApp

- import_tasks: bigip_appIntentData_get.yaml
  tags:
    - buildApp

- import_tasks: bigip_appIntentData_remove.yaml
  tags:
    - buildApp

- import_tasks: bigip_wait.yaml
  tags:
    - buildApp

- import_tasks: bigip_as3_rpms.yaml
  tags:
    - buildApp

- import_tasks: bigip_wait.yaml
  tags:
    - buildApp

- import_tasks: bigip_as3Onboarding.yaml
  when: active_host == True
  tags:
    - buildApp

