- name: Initializing the custom variables used in branching
  vars:
  set_fact:
    pool_statuses: {}

- name: COLLECT BIG-IP ltm Pools for "{{ inventory_hostname }}" using the FACTS module
  bigip_device_info:
    provider: "{{ provider }}"
    gather_subset:
      - ltm-pools
  register: pools

- name: Extracting the status of the pools
  set_fact:
    pool_statuses: "{{ pool_statuses|default({}) | combine({item.name:item.availability_status})}}"
  loop: "{{ pools.ltm_pools }}"

- name: Copy output to file
  copy:
    content: "{{ pool_statuses }}"
    dest: "{{role_path}}/tmp/new_status.json"
