---
- name: Map in DNS "{{ inventory_hostname }}" to IP "{{ VirtualMachine_Network0_Address }}"
  nios_host_record:
    name: "{{inventory_hostname}}"
    ipv4:
      - address: "{{ VirtualMachine_Network0_Address }}"
    state: present
    provider: "{{nios_provider}}"
