- name: cleanup and clone
  block:
    - name: Check if the repos dir is empty
      find:
        paths: "{{ role_path }}/tmp/repos/"
        patterns: "*.*"
        recurse: yes
      register: foundFiles

    - name: Cleaning up the repos directory if not empty
      file:
        path: "{{ role_path }}/tmp/repos"
        state: absent
      when: foundFiles.matched > 0

    - git:
        repo: git@github.com:arunhotra/infra-repo.git
        dest: "{{role_path}}/tmp/repos"
        accept_hostkey: true
  run_once: true

- name: Poplulate files from template for generating JSON specific to each BIG-IP
  template:
    src: "bigip.j2"
    dest: "{{role_path}}/tmp/repos/virtualDataCenter/{{inventory_hostname_short}}.json"

- name: Push the BIG-IP specific JSON files to the Infrastructure repository
  shell: git config --global user.name "arunganti" ; git config --global user.email "a.ganti@f5.com" ; git add . ; git commit -m "onboarded ha pair" ; git push origin master
  args:
    chdir: "{{role_path}}/tmp/repos"
  run_once: true
