
  # - name: Ensure server is present in known_hosts file
  #   known_hosts:
  #     name: "github.com"
  #     state: present
  #     key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"


  - name: cleanup and clone
    block:
      - name: Check if the repos dir is empty 
        find:
          paths: "{{ role_path }}/tmp/repos/"
          patterns: '*.*'
          recurse: yes
        register: foundFiles
        
      - name: Cleaning up temporary directories prior to getting intent data
        file:
          path: "{{ role_path }}/tmp/repos"
          state: absent
        when: foundFiles.matched > 0

      - git:
          repo: git@github.com:arunhotra/infra-repo.git
          dest: "{{role_path}}/tmp/repos"
          accept_hostkey: true
    run_once: true


  # - name: Print rendered DO declaration
  #   debug:
  #     msg: "{\"Build SOT Template\": {{ lookup('template','{{ role_path }}/templates/bigip.j2') }}}"

  - name: Poplulate files from template
    template:
      src: 'bigip.j2'
      # src: "{{ lookup('template','{{ role_path }}/templates/bigip.j2') }}}"
      dest: "{{role_path}}/tmp/repos/virtualDataCenter/{{inventory_hostname_short}}.json"

  - name: Change the working directory to somedir/ before executing the command
    shell: git config --global user.name "arunganti" ; git config --global user.email "a.ganti@f5.com" ; git add . ; git commit -m "onboarded ha pair" ; git push origin master
    args:
      chdir: "{{role_path}}/tmp/repos"