- import_tasks: build_provider.yaml
  tags:
    - testAppsCurrent

- import_tasks: populate_status.yaml
  tags:
    - testAppsCurrent

- import_tasks: populate_pool_status.yaml
  when: active_host == True
  tags:
    - testAppsCurrent
